#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;35m'
NC='\033[0m' # No Color


shopt -s globstar

function setup {
    return
}
function destroy {
    return
}
function setupTest {
    return
}
function destroyTest {
    return
}

# execute all test in a single unit $1 is the units file name
function execute-test {
        func=$(grep "function Test.*{" "$1" | sed 's:function ::' | sed 's: {::')
        for unitTest in $func; do
                echo -e "$BLUE Running test: $unitTest $NC"
                setupTest
                "$unitTest"
                destroyTest
        done
}

# $1 is the file
function run-unit {
    # get the file comment
    desc=$(head -n1 "$1" | sed 's:^#::')
    # print out the file comment
    echo -e "$BLUE$desc$NC"
    # load in the file
    source "$1"
    # perform initial setup
    setup
    
    execute-test "$1"

    # perform destruction
    destroy
}

# $1 is the path to shUnit
function iterate {
    for unit in **/*.shUnit; do
        if [[ -f "$unit" ]]; then
           echo -e "$BLUE Running unit: $NC$unit"
           "$1" -r "$unit"
           echo -e "$BLUE--------------------------------------------------------$NC"
        fi
    done 
}


if [[ "$1" == "-r" ]]; then
        run-unit "$2"
else
        iterate "$0"
fi

